apiVersion: v1
kind: Service
metadata:
  name: berglas-aws-webhook
  labels:
    app: berglas-aws-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: berglas-aws-webhook
